# Generated by Django 5.2.5 on 2025-08-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ref', models.CharField(help_text='Patient reference ID (no PHI)', max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encounters',
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveIntegerField()),
                ('file_path', models.CharField(help_text='S3 object key', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('format', models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('m4a', 'M4A')], max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('committed', 'Committed'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='encounters.encounter')),
            ],
            options={
                'db_table': 'audio_chunks',
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.PositiveIntegerField()),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, help_text='STT confidence score', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='encounters.audiochunk')),
            ],
            options={
                'db_table': 'transcript_segments',
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['doctor', 'created_at'], name='encounters_doctor__0c8642_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient_ref'], name='encounters_patient_154d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='encounters_status_2bbb51_idx'),
        ),
        migrations.AddIndex(
            model_name='audiochunk',
            index=models.Index(fields=['encounter', 'chunk_number'], name='audio_chunk_encount_286e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiochunk',
            index=models.Index(fields=['status'], name='audio_chunk_status_ae619b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audiochunk',
            unique_together={('encounter', 'chunk_number')},
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['audio_chunk', 'segment_number'], name='transcript__audio_c_57ad8e_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['start_time'], name='transcript__start_t_2a64c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transcriptsegment',
            unique_together={('audio_chunk', 'segment_number')},
        ),
    ]
