# Generated by Django 5.2.5 on 2025-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('reset_password', 'Password Reset')], max_length=20)),
            ],
            options={
                'db_table': 'phone_verifications',
                'indexes': [models.Index(fields=['phone_number', 'code'], name='phone_verif_phone_n_ed033c_idx'), models.Index(fields=['created_at'], name='phone_verif_created_4acb3f_idx')],
            },
        ),
    ]
