# Generated by Django 5.2.5 on 2025-08-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, unique=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('last_check_at', models.DateTimeField(auto_now=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'integration_health',
            },
        ),
        migrations.CreateModel(
            name='ExternalServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('crazy_miner', 'Crazy Miner'), ('helssa', 'Helssa'), ('openai', 'OpenAI/GapGPT')], max_length=20)),
                ('action', models.CharField(choices=[('otp_send', 'OTP Send'), ('otp_verify', 'OTP Verify'), ('sms_send', 'SMS Send'), ('patient_search', 'Patient Search'), ('patient_info', 'Patient Info'), ('access_verify', 'Access Verify'), ('health_check', 'Health Check')], max_length=20)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_data', models.JSONField(default=dict, help_text='Request data (sanitized)')),
                ('request_headers', models.JSONField(default=dict, help_text='Request headers (sanitized)')),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(default=dict, help_text='Response data (sanitized)')),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_service_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_service_logs',
                'indexes': [models.Index(fields=['service', 'action'], name='external_se_service_408255_idx'), models.Index(fields=['success', 'created_at'], name='external_se_success_c96ab9_idx'), models.Index(fields=['user', 'created_at'], name='external_se_user_id_1c2b4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('otp_id', models.CharField(blank=True, help_text='Crazy Miner OTP ID', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('send_attempts', models.IntegerField(default=0)),
                ('verify_attempts', models.IntegerField(default=0)),
                ('max_verify_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True)),
                ('verified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_sessions',
                'indexes': [models.Index(fields=['phone_number', 'status'], name='otp_session_phone_n_517411_idx'), models.Index(fields=['otp_id'], name='otp_session_otp_id_14a6f1_idx'), models.Index(fields=['expires_at'], name='otp_session_expires_54e401_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ref', models.CharField(help_text='Patient reference ID', max_length=100)),
                ('access_granted', models.BooleanField(default=False)),
                ('access_level', models.CharField(default='read_only', max_length=20)),
                ('helssa_session_id', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_access_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_access_sessions',
                'indexes': [models.Index(fields=['user', 'patient_ref'], name='patient_acc_user_id_50a737_idx'), models.Index(fields=['access_granted', 'expires_at'], name='patient_acc_access__d9ae45_idx')],
                'unique_together': {('user', 'patient_ref')},
            },
        ),
    ]
