# Generated by Django 5.2.5 on 2025-08-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('down', 'Down')], max_length=20)),
                ('message', models.TextField()),
                ('metrics', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['component', 'status'], name='adminplus_s_compone_634a19_idx'), models.Index(fields=['checked_at'], name='adminplus_s_checked_c60766_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('retry', 'Retry'), ('failure', 'Failure'), ('success', 'Success')], max_length=20)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name', 'status'], name='adminplus_t_task_na_1a6fa3_idx'), models.Index(fields=['status', 'created_at'], name='adminplus_t_status_47ee8d_idx'), models.Index(fields=['created_at'], name='adminplus_t_created_777477_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('task_retry', 'Task Retry'), ('task_cancel', 'Task Cancel'), ('system_maintenance', 'System Maintenance'), ('data_export', 'Data Export'), ('user_action', 'User Action'), ('system_config', 'System Configuration')], max_length=50)),
                ('description', models.TextField()),
                ('target_object', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='adminplus_o_user_id_284e04_idx'), models.Index(fields=['action', 'created_at'], name='adminplus_o_action_7e44bd_idx'), models.Index(fields=['created_at'], name='adminplus_o_created_835135_idx')],
            },
        ),
    ]
