version: '3.8'

services:
  monitor:
    build: .
    container_name: soapify_monitor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./test_audio:/app/test_audio
      - ./reports:/app/reports
      - ./test_results.db:/app/test_results.db
    environment:
      - API_BASE_URL=https://django-m.chbk.app
      - TEST_INTERVAL_MINUTES=5
      - DATABASE_URL=sqlite:///./test_results.db
    networks:
      - monitor_network

  redis:
    image: redis:7-alpine
    container_name: monitor_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - monitor_network

  prometheus:
    image: prom/prometheus
    container_name: monitor_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitor_network

  grafana:
    image: grafana/grafana
    container_name: monitor_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitor_network

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  monitor_network:
    driver: bridge