# Generated by Django 5.2.5 on 2025-08-22 09:39

import django.db.models.deletion
import django.utils.timezone
import uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_committed', models.BooleanField(default=False)),
                ('final_file', models.FileField(blank=True, null=True, upload_to=uploads.models.upload_to_sessions)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=16)),
                ('s3_object_key', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=uploads.models.upload_to_audio)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.audiosession')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('session', 'chunk_index')},
            },
        ),
    ]
